# Generated by Django 5.2.7 on 2025-10-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_articles_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='anons',
        ),
        migrations.AddField(
            model_name='articles',
            name='summary',
            field=models.CharField(default='', max_length=250, verbose_name='Summary'),
        ),
    ]
