# Generated by Django 5.2.7 on 2025-11-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publication Date'),
        ),
    ]
